const assert=require('node:assert/strict'),{test}=require('node:test'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function load(name){const scope={exports:{},require:p=>load(path.basename(p))};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,`../lib/${name}.ts`),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,scope);return scope.exports}
const {SketchHistory}=load('sketchbook-history');
const empty=()=>({strokes:[],background:'#fffaf0',width:900,height:560,activeLayer:'outline',layers:{outline:{visible:true,opacity:1},color:{visible:true,opacity:1}}});
const add=(d,n)=>({...d,strokes:[...d.strokes,{id:String(n),width:8,color:'#000000',erase:false,points:[{x:.1,y:.1},{x:.2,y:.3}]}]});
test('연속 호출에서도 3개 선이 정확히 하나씩 취소/복구된다',()=>{const h=new SketchHistory();let d=empty();for(let i=0;i<3;i++){const next=add(d,i);h.record(d,next);d=next}for(let n=2;n>=0;n--){d=h.undo(d);assert.equal(d.strokes.length,n)}for(let n=1;n<=3;n++){d=h.redo(d);assert.equal(d.strokes.length,n)}});
test('선택, 동일 색, 원위치 레이어/올가미 변경은 스택과 redo를 건드리지 않는다',()=>{const h=new SketchHistory(),a=empty(),b=add(a,1);h.record(a,b);h.undo(b);for(const next of [{...a,activeLayer:'color'},{...a,layers:{outline:{visible:true,opacity:1},color:{visible:true,opacity:1}}},{...a,background:a.background}])assert.equal(h.record(a,next),false);assert.equal(h.future.length,1);assert.equal(h.record(b,{...b,strokes:b.strokes.map(s=>({...s,points:s.points.map(p=>({...p}))}))}),false)});
test('레이어 제스처는 시작과 끝 사이 한 단계로 복구되고 취소 후 새 선은 redo를 비운다',()=>{const h=new SketchHistory(),a=add(empty(),1),b={...a,layers:{...a.layers,color:{visible:true,opacity:.4}}};h.record(a,b);assert.equal(h.undo(b).layers.color.opacity,1);h.record(a,add(a,2));assert.equal(h.future.length,0);assert.equal(h.undo(add(a,2)).strokes.length,1)});
test('50회 제한과 다시 실행은 같은 순서를 유지한다',()=>{const h=new SketchHistory();let d=empty();for(let i=0;i<60;i++){const n=add(d,i);h.record(d,n);d=n}assert.equal(h.past.length,50);for(let i=0;i<50;i++)d=h.undo(d);assert.equal(d.strokes.length,10);assert.equal(h.undo(d),null);for(let i=0;i<50;i++)d=h.redo(d);assert.equal(d.strokes.length,60);assert.equal(h.redo(d),null)});
