const assert=require('node:assert/strict'),{test}=require('node:test'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function load(name){const scope={exports:{},require:p=>load(path.basename(p))};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,`../lib/${name}.ts`),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,scope);return scope.exports}
const {pinchView,TouchView,IDENTITY,draggedValue,hexToHsv,hsvToHex,pencilGrain}=load('sketchbook-controls');
const {transformSelection,selectionBounds}=load('sketchbook');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('확대와 이동을 함께 해도 손가락 사이의 원본 위치를 유지한다',()=>{const v={scale:2,x:30,y:-10},start=[{x:20,y:40},{x:100,y:40}],next=[{x:-10,y:80},{x:150,y:80}],n=pinchView(v,start,next);close(n.scale,4);close((60-v.x)/v.scale,(70-n.x)/n.scale);close((40-v.y)/v.scale,(80-n.y)/n.scale)});
test('줌 상한에서도 중심을 유지하고 0 거리에서 유한한 값을 반환한다',()=>{const n=pinchView(IDENTITY,[{x:0,y:0},{x:0,y:0}],[{x:-1000,y:0},{x:1000,y:0}]);assert.equal(n.scale,6);assert.equal(n.x,0);assert.ok(Number.isFinite(n.y));assert.equal(pinchView(IDENTITY,[{x:-10,y:0},{x:10,y:0}],[{x:0,y:0},{x:0,y:0}]).scale,.5)});
test('두번째 터치부터 펜/채우기를 취소하고, 모두 뗄 때까지 그리기를 잠근다',()=>{const g=new TouchView();assert.equal(g.down(1,{x:0,y:0},IDENTITY),false);assert.equal(g.down(2,{x:30,y:0},IDENTITY),true);assert.equal(g.move(2,{x:60,y:0}).scale,2);assert.equal(g.up(1,IDENTITY),true);assert.equal(g.locked,true);assert.equal(g.move(2,{x:70,y:0}),null);assert.equal(g.up(2,IDENTITY),true);assert.equal(g.locked,false);assert.equal(g.down(3,{x:10,y:0},IDENTITY),false)});
test('세 번째 손가락과 취소가 들어와도 다음 제스처가 정상 시작된다',()=>{const g=new TouchView();g.down(1,{x:0,y:0},IDENTITY);g.down(2,{x:30,y:0},IDENTITY);g.down(3,{x:10,y:10},IDENTITY);g.up(1,IDENTITY);assert.equal(g.move(3,{x:10,y:20}).scale>0,true);g.reset();assert.equal(g.points.size,0);assert.equal(g.locked,false)});
test('원형 조절은 위로 끌면 증가하고 범위를 넘지 않는다',()=>{assert.ok(draggedValue(40,-20,2,96)>40);assert.ok(draggedValue(40,20,2,96)<40);assert.equal(draggedValue(40,-9999,2,96),96);assert.equal(draggedValue(40,9999,1,100),1)});
test('팔레트·스포이드·휠 간 색 변환은 원래 RGB를 보존한다',()=>{for(const c of ['#000000','#ffffff','#808080','#b84839','#edaa35','#00ff88','#3252f1']){const {h,s,v}=hexToHsv(c);assert.equal(hsvToHex(h,s,v),c)}});
test('색연필 종이결은 결정적이고 촘촘한 심지 입자와 다양한 농도를 포함한다',()=>{const a=pencilGrain('#b84839'),b=pencilGrain('#b84839');assert.deepEqual(a,b);const alpha=Array.from(a).filter((_,i)=>i%4===3),gaps=alpha.filter(x=>x===0).length;assert.ok(gaps>300&&gaps<1000);assert.ok(new Set(alpha).size>100);assert.equal(a[0],184);assert.equal(a[1],72);assert.equal(a[2],57);const t=performance.now();for(let i=0;i<16;i++)pencilGrain('#b84839');console.log('16 cached-color tile initializations ms:',(performance.now()-t).toFixed(1))});
const strokes=[{id:'a',width:8,color:'#000000',erase:false,points:[{x:.3,y:.3},{x:.5,y:.5}]},{id:'b',width:4,color:'#ffffff',erase:false,points:[{x:.1,y:.1}]}];
test('8개 조절점은 반대편을 고정하고 원본과 다른 선을 보존한다',()=>{const before=JSON.stringify(strokes);for(const h of ['n','ne','e','se','s','sw','w','nw']){const end={x:h.includes('w')?.2:.6,y:h.includes('n')?.2:.6};const n=transformSelection(strokes,['a'],h,{x:.5,y:.5},end);const b=selectionBounds(n,['a']);if(h.includes('e'))close(b.left,.3);if(h.includes('w'))close(b.right,.5);if(h.includes('n'))close(b.bottom,.5);if(h.includes('s'))close(b.top,.3);assert.equal(n[1],strokes[1]);}assert.equal(JSON.stringify(strokes),before)});
test('세로 종이에서 90도 회전해도 실제 픽셀 길이와 중심은 같다',()=>{const W=900,H=1300,c={x:.4,y:.4},n=transformSelection(strokes,['a'],'rotate',{x:c.x,y:c.y-.1},{x:c.x+.1,y:c.y},W,H);const [a,b]=n[0].points;close(Math.hypot((b.x-a.x)*W,(b.y-a.y)*H),Math.hypot(.2*W,.2*H));close((a.x+b.x)/2,c.x);close((a.y+b.y)/2,c.y)});
test('종이 밖으로 회전하거나 조절점을 지나쳐도 좌표는 안전하며 반전되지 않는다',()=>{const edge=[{...strokes[0],points:[{x:0,y:0},{x:1,y:1}]}];for(const h of ['rotate','se','nw']){const n=transformSelection(edge,['a'],h,{x:.5,y:0},{x:2,y:-3},900,1300);for(const p of n[0].points){assert.ok(p.x>=-1e-9&&p.x<=1+1e-9);assert.ok(p.y>=-1e-9&&p.y<=1+1e-9)}}});
